import {StyleSheet, Platform, Dimensions} from 'react-native';
import {color} from '../../Reusedcomponents/color';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export const styles = StyleSheet.create({
  text: {
    //     backgroundColor: '#F3F5F7',
    backgroundColor: 'white',
    height: hp('8'),
    width: wp('75'),
    alignSelf: 'center',
    fontSize: hp('2.5'),
    //     marginLeft:wp('4%')
  },
  topTitle: {
    color: color.textSecondaryColor,
    textAlign: 'center',
    marginTop: hp('2'),
    fontSize: hp('2.3'),
  },
  topTitle2: {
    color: color.textSecondaryColor,
    marginTop: hp('2'),
    fontSize: hp('2.3'),
    marginLeft: wp('7'),
  },
  topButtonView: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: wp('100'),
    marginTop: hp('2'),
  },
  topActiveButton: {
    width: wp('40'),
    borderRadius: 5,
    borderWidth: 0.8,
    height: hp('5'),
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: color.textPrimaryColor,
  },
  topInactiveButton: {
    width: wp('40'),
    borderRadius: 5,
    borderWidth: 0.8,
    height: hp('5'),
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: color.borderThirdColor,
  },
  topActiveText: {
    color: color.textPrimaryColor,
    fontSize: hp('2'),
  },
  topInactiveText: {
    color: 'gray',
    fontSize: hp('2'),
  },
  billSummaryView: {
    width: wp('90'),
    alignSelf: 'center',
    marginTop: hp('2'),
  },
  innerContainer: {
    flexDirection: 'row',
    width: wp('45'),
    marginBottom: hp('1'),
  },
  innerText: {color: '#434345', fontSize: hp('2')},
  totalSubTitle: {
    alignSelf: 'flex-end',
    fontSize: hp('1.5'),
    color: 'black',
  },
  textContainer: {width: wp('45')},
  radioText: {
    // marginTop: hp('0.9'),
    color: 'gray',
    marginLeft: wp('3'),
  },
  paymentRadioButtonView: {
    flexDirection: 'row',
    // backgroundColor: 'yellow',
    alignItems: 'center',
    marginBottom: hp('-1.5'),
  },
  radioButtonText: {
    color: 'black',
    fontSize: hp('2.3'),
  },
  cartButton: {
    height: hp('7'),
    width: wp('85'),
    borderRadius: 5,
    backgroundColor: color.textPrimaryColor,
    position: 'absolute',
    bottom: Platform?.OS == 'ios' ? 110 : 20,
    alignSelf: 'center',
  },
  textCart: {
    flex: 1,
    flexDirection: 'row',
    textAlign: 'center',
    textAlignVertical: 'center',
    color: color.white,
    fontFamily: 'Poppins-SemiBold',
    fontSize: hp('2'),
  },
  informationView: {
    alignSelf: 'center',
    marginTop: hp('-5'),
    marginBottom: hp('2'),
  },
  centerText: {
    marginLeft: wp('8'),
    color: color.defaultcolor,
    marginTop: wp('4'),
  },
  checkBoxButtonContainer: {
    marginTop: hp('2'),
    marginLeft: wp('4'),
  },
  box: {
    padding: 13,
    margin: wp('7'),
    marginBottom: hp('1'),
    backgroundColor: 'white',
    //     backgroundColor: '#F3F5F7',
    shadowColor: '#000',
    shadowOpacity: 0.4,
    shadowOffset: {width: 1, height: 3},
    shadowRadius: 2,
    elevation: 5,
    // height: hp('30'),
    borderRadius: 10,
  },
  checkStyle: {
    borderWidth: 0.5,
    borderColor: color.themColorPrimary,
    // borderRadius: 60,
    borderRadius: Math.round(
      Dimensions.get('window').width + Dimensions.get('window').height,
    ),
    width: Dimensions.get('window').width * 0.08,
    height: Dimensions.get('window').width * 0.08,
    width: wp('8.5'),
    height: hp('4.1'),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: wp('2'),
  },
});
